### ISSUE TITLE
Temas para palestras da Codecon Digital 2021

### ISSUE THREAD

**Issue by gabrnunes** [codecon-dev/codecon-digital#1]
Deixe um comentário com algum tema ou pessoa que você quer ver na Codecon 2021. Este ano teremos 9 palestras em 3 dias de evento.

O evento será transmitido ao vivo pela Twitch e haverá perguntas e uma entrevista com o palestrante.

Se você curtiu algum tema, deixe uma reação (isso vai contar pra gente analisar).

Acesse nosso grupo no Discord: http://codecon.dev/discord
Siga a gente no Twitter para mais novidades: http://twitter.com/codecondev

**Comment by KamyllaJawad** [comment]
Ciência de dados

**Comment by dev-danilosilva** [comment]
Temas ligados à programação funcional com linguagens  como Haskell, Clojure, Elixir, OCaml ou Scala

**Comment by NicolasPereira** [comment]
Temas ligados para iniciantes na programação, discussão sobre carreira para quem está começando e afins!

**Comment by RichardDev** [comment]
Refatoração e qualidade de software

**Comment by murillo94** [comment]
Aplicações com react-native + react-native-web
