### ISSUE TITLE
Temas para workshops na Codecon 2021

### ISSUE THREAD

**Issue by gabrnunes** [codecon-dev/codecon-digital#2]
Deixe um comentário com algum tema ou pessoa que você quer ver um workshop na Codecon 2021. Este ano teremos 6 workshops em 3 dias de evento.

Os workshops terão um valor de R$ 29 por inscrição e serão ao vivo pelo Google Meet.

Se você curtiu algum tema, deixe uma reação (isso vai contar pra gente analisar).

Acesse nosso grupo no Discord: http://codecon.dev/discord
Siga a gente no Twitter para mais novidades: http://twitter.com/codecondev

**Comment by KamyllaJawad** [comment]
Ciência de dados, cybersecurity, devops

**Comment by luacks** [comment]
Testes no Front End

**Comment by andrecampll** [comment]
Testes no frontend com React

**Comment by andrecampll** [comment]
Algum workshop com Elixir

**Comment by dev-danilosilva** [comment]
Kubernetes

**Comment by murillo94** [comment]
react-native + react-native-web

**Comment by ellisonleao** [comment]
"Matando sua IDE e mostrando o NeoVim"

**Comment by tavareshenrique** [comment]
**- NextJS**
     * NextJS tem ganhado cada vez mais o coração dos dev's Front-End, seria bacana alguma coisa com o tema; 
**- Performance no ReactJS;**
     * Considero um assunto muito didádico e importante; 
**- TypeScript;**
     * Seria legal algum assunto relacionado a produtividade etc. no TS;
**- Cypress**
     * Citaram muito testes no Front-End, o Cypress pode ser uma ferramenta legal para ser abordada;
**- Micro Frontends;**
     * É um assunto que tenho zero conhecimentos e gostaria de saber mais sobre;
**- Electron;**
     * Excelente alternativa para quem está querendo desenvolver aplicações Desktop utilizando o JS, existe hoje pouquíssimos assuntos brasileiros, acredito eu, sobre o tema;
